package models

type FieldType int

const (
	_ FieldType = iota
	FieldType_Age
	FieldType_Date
	FieldType_Place
	FieldType_Gender
	FieldType_Name
	FieldType_Role
	FieldType_Years
	FieldType_Months
	FieldType_Days
	FieldType_Hours
	FieldType_Minutes
	FieldType_Year
	FieldType_Month
	FieldType_Day
	FieldType_Hour
	FieldType_Minute
	FieldType_Address
	FieldType_Cemetery
	FieldType_City
	FieldType_Church
	FieldType_County
	FieldType_Country
	FieldType_District
	FieldType_Hospital
	FieldType_Island
	FieldType_MilitaryBase
	FieldType_Mortuary
	FieldType_Parish
	FieldType_PlotNumber
	FieldType_PostOffice
	FieldType_PostalCode
	FieldType_Prison
	FieldType_Province
	FieldType_Section
	FieldType_Ship
	FieldType_State
	FieldType_Territory
	FieldType_Town
	FieldType_Township
	FieldType_Ward
	FieldType_Prefix
	FieldType_Suffix
	FieldType_Given
	FieldType_Surname
	FieldType_Abusua
	FieldType_BatchNumber
	FieldType_Caste
	FieldType_Clan
	FieldType_CommonLawMarriage
	FieldType_Education
	FieldType_Ethnicity
	FieldType_FatherBirthPlace
	FieldType_NeverHadChildren
	FieldType_NeverMarried
	FieldType_NumberOfChildren
	FieldType_NumberOfMarriages
	FieldType_Household
	FieldType_IsHeadOfHousehold
	FieldType_MaritalStatus
	FieldType_MotherBirthPlace
	FieldType_MultipleBirth
	FieldType_NameSake
	FieldType_NationalId
	FieldType_Nationality
	FieldType_Occupation
	FieldType_PhysicalDescription
	FieldType_Property
	FieldType_Race
	FieldType_Religion
	FieldType_RelationshipToHead
	FieldType_Stillbirth
	FieldType_TitleOfNobility
	FieldType_Tribe
)
